use_default_settings: true

server:
  limiter: false

search:
  formats:
    - html
    - json

engines:
  - name: bing
    disabled: false
  - name: mojeek
    disabled: false
  - name: qwant
    disabled: false
  - name: yahoo
    disabled: false
