global:
  scrape_interval: 15s

scrape_configs:
  - job_name: mooncellar-backend
    metrics_path: /metrics
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/metrics_token
    static_configs:
      - targets: ["mooncellar-backend:3228"]
