export enum Genres {
  INDIE = "Indie",
  ADVENTURE = "Adventure",
  SIMULATOR = "Simulator",
  STRATEGY = "Strategy",
  RPG = "Role-playing (RPG)",
  PUZZLE = "Puzzle",
  SHOOTER = "Shooter",
  ARCADE = "Arcade",
  PLATFORM = "Platform",
  SPORT = "Sport",
  RACING = "Racing",
  VN = "Visual Novel",
  POINT_AND_CLICK = "Point-and-click",
  FIGHTING = "Fighting",
  CARD = "Card & Board Game",
  TBS = "Turn-based strategy (TBS)",
  SLASHER = "Hack and slash/Beat 'em up",
  MUSIC = "Music",
  TACTICAL = "Tactical",
  RTS = "Real Time Strategy (RTS)",
  QUIZ = "Quiz/Trivia",
  PINBALL = "Pinball",
  MOBA = "MOBA",
}
