name: CI/CD

on:
  push:
  pull_request:

env:
  IMAGE_NAME: mooncellar-frontend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3.12'

      - name: Install dependencies
        env:
          HUSKY: 0
        run: bun install --frozen-lockfile

      - name: Run lint
        run: bun run lint

      - name: Run format check
        run: bun run format

      # - name: Check commit messages
      #   uses: wagoid/commitlint-github-action@v3
      #   with:
      #     configFile: commitlint.config.cjs

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: echo "SSH works!"

      - name: Build image
        run: |
          echo "${{ secrets.HOST_ENV }}" > .env;
          podman build \
            -t $IMAGE_NAME:latest \
            .

      - name: Save image as tar
        run: |
          podman save $IMAGE_NAME:latest | gzip > image.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "image.tar.gz"
          target: "/tmp/"

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            podman load < /tmp/image.tar.gz

            cd ${{ secrets.WORK_DIR }}
            ../run.sh
            systemctl --user daemon-reload
            systemctl restart --user Mooncellar-Frontend.service

            podman image prune -f
            rm /tmp/image.tar.gz
